# From-scratch Hex5 numerical-Q21 trial.

defaults:
  - hex
  - _self_

run:
  max_num_iters: 40

env:
  board_size: 5


selfplay:
  max_num_steps: 25

eval:
  checkpoint_path: checkpoints/5_solved

checkpointing:
  max_to_keep: 0
  save_interval_steps: 1
  directory: checkpoints/asd
