# From-scratch Hex6 numerical-Q21 trial.

defaults:
  - hex
  - _self_

run:
  max_num_iters: 50

env:
  board_size: 6

model:
  num_channels: 128
  num_layers: 6

selfplay:
  batch_size: 4096
  max_num_steps: 36

eval:
  checkpoint_path: checkpoints/6_solved

checkpointing:
  max_to_keep: 0
  save_interval_steps: 10
  directory: checkpoints/asd
